name = "Xoxticit MC"
author = "EthicalObligation"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77eac21bb0545774a07c1574ebcf7dad62849de1b0b18e122004e98098d9f62a"

[versions]
forge = "36.0.0"
minecraft = "1.16.5"
